# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --display_data=true
    # <- Optional: specify video codec (h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm"
```
"""

import logging
import os
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.processor import make_default_processors
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    RobotConfig,
    bi_openarm_follower,
    bi_piper_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    piper_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from lerobot.scripts.recording_hil import (
    ACPInferenceConfig,
    PolicySyncDualArmExecutor,
    _capture_policy_runtime_state,  # noqa: F401
    _predict_policy_action_with_acp_inference,  # noqa: F401
)
from lerobot.scripts.recording_loop import record_loop
from lerobot.teleoperators import (  # noqa: F401
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_piper_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    piper_leader,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.utils.constants import ACTION
from lerobot.utils.piper_sdk import PIPER_JOINT_NAMES
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    sanity_check_bimanual_piper_pair,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.recording_annotations import (
    EPISODE_FAILURE,
    infer_collector_policy_id,
    normalize_episode_success_label,
)
from lerobot.utils.recording_events import EventConfig
from lerobot.utils.utils import (
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun


# Default home pose for piper arms, mirroring src/lerobot/reset.py: all six joints at 0 via raw
# JointCtrl (bypassing calibration), gripper opened, so leader + follower land on the same
# hardware home regardless of their individual calibration.
_PIPER_HOME_JOINTS = (0, 0, 0, 0, 0, 0)
_PIPER_HOME_GRIPPER = 70000
_PIPER_HOME_SPEED = 50
# 第一个 episode 启动归位用更低的 MotionCtrl 速率（百分比），现场可能无人值守，慢速更安全。
_PIPER_HOME_SLOW_SPEED = 20
_PIPER_HOME_SETTLE_S = 3.0
# 主臂平滑归位的插值时长/步长（参考 reset.py 的 control_arm_smooth）：0xAD 下 speed 不生效，
# 用 duration/step_dt 个小步逐步逼近目标来自己控速，整体快慢由 duration 决定，与模式无关。
_PIPER_HOME_SMOOTH_DURATION_S = 4.0
_PIPER_HOME_SMOOTH_STEP_DT_S = 0.02
# 用户显式按 ← 要求重录时，不立刻开始下一次记录，而是先等待这么多秒，
# 给操作者复位/准备的时间，并在命令行做整秒倒计时提示。
_RERECORD_DELAY_S = 2.0


def _countdown_before_rerecord(delay_s: float, play_sounds: bool) -> None:
    """显式按 ← 重录后，开始下一次记录前的倒计时等待，并在命令行逐秒提示。"""
    total = int(round(delay_s))
    log_say(f"Re-recording in {total} seconds", play_sounds)
    for remaining in range(total, 0, -1):
        logging.info(f"[重录] 将在 {remaining} 秒后开始记录…")
        time.sleep(1.0)
    logging.info("[重录] 开始记录。")


def _home_piper_arm(arm, speed: int = _PIPER_HOME_SPEED) -> None:
    # Position-velocity mode (mit_mode=0x00) + raw zero joints, exactly like reset.py.
    arm.MotionCtrl_2(0x01, 0x01, speed, 0x00)
    arm.JointCtrl(*_PIPER_HOME_JOINTS)
    arm.GripperCtrl(_PIPER_HOME_GRIPPER, 1000, 0x01, 0)


def _home_leader_arm_smooth(
    arm,
    mit_mode: int,
    speed: int = _PIPER_HOME_SLOW_SPEED,
    duration_s: float = _PIPER_HOME_SMOOTH_DURATION_S,
    step_dt_s: float = _PIPER_HOME_SMOOTH_STEP_DT_S,
) -> None:
    """参考 reset.py 的 control_arm_smooth：把主臂从“当前位姿”插值到全零目标，逐步小步下发并自己控速。

    主臂在 0xAD(MIT high-follow) 下 MotionCtrl_2 的 speed 不生效，单条 JointCtrl 会全速急冲到目标。
    这里把“一次大跳”拆成 duration_s/step_dt_s 个小步、每步 sleep，复刻 reset.py 实时镜像时“高频小步”
    的平滑慢速归位；整体时长由 duration_s 决定，与模式无关。函数阻塞约 duration_s 秒后返回。
    """
    goal = list(_PIPER_HOME_JOINTS)
    start, _ = _read_arm_raw_joints(arm)
    steps = max(int(duration_s / step_dt_s), 1)
    for s in range(1, steps + 1):
        ratio = s / steps
        cmd = [int(start[i] + (goal[i] - start[i]) * ratio) for i in range(6)]
        if cmd[4] < -70000:  # 与 reset.py 一致：joint_4 下限保护
            cmd[4] = -70000
        arm.MotionCtrl_2(0x01, 0x01, speed, mit_mode)  # 保持模式刷新（0xAD 下 speed 仅占位）
        arm.JointCtrl(*cmd)
        time.sleep(step_dt_s)
    arm.GripperCtrl(_PIPER_HOME_GRIPPER, 1000, 0x01, 0)


def _read_arm_raw_joints(arm) -> tuple[list[int], int]:
    """Read an arm's live joint + gripper feedback in raw piper units (same units JointCtrl expects)."""
    joint_msg = arm.GetArmJointMsgs()
    joint_state = getattr(joint_msg, "joint_state", None)
    joints = [int(getattr(joint_state, joint_name, 0)) for joint_name in PIPER_JOINT_NAMES]

    gripper_msg = arm.GetArmGripperMsgs()
    gripper_state = getattr(gripper_msg, "gripper_state", None)
    gripper = abs(int(getattr(gripper_state, "grippers_angle", 0)))
    return joints, gripper


def _hold_piper_arm(arm, joints: list[int], gripper: int, speed: int = _PIPER_HOME_SPEED) -> None:
    """Lock a piper arm stiff at the given joint/gripper pose (position-velocity mode)."""
    arm.MotionCtrl_2(0x01, 0x01, speed, 0x00)
    arm.JointCtrl(*joints)
    arm.GripperCtrl(gripper, 1000, 0x01, 0)


def _hold_arms_current_pose(robot, teleop, leader_action: dict[str, float] | None = None) -> None:
    """Hold can0 at can1's last accepted action and lock can1 at its live pose."""
    held_any = False

    # Reuse the exact common-coordinate action that can1 accepted. PiperLeader.send_feedback handles
    # the calibration round-trip and safely leaves gravity-comp mode before applying this target.
    if teleop is not None and not isinstance(teleop, list):
        leader_arm = getattr(teleop, "arm", None)
        if leader_arm is not None and hasattr(leader_arm, "JointCtrl"):
            if leader_action is None:
                logging.warning("Leader hold skipped: can1 has not accepted an action yet.")
            else:
                teleop.send_feedback(leader_action)
                held_any = True

    follower_arm = getattr(robot, "arm", None)
    if follower_arm is not None and hasattr(follower_arm, "JointCtrl"):
        joints, gripper = _read_arm_raw_joints(follower_arm)
        _hold_piper_arm(follower_arm, joints, gripper)
        held_any = True

    if held_any:
        logging.info("Episode ended: leader + follower holding current pose until next episode.")
    else:
        logging.warning("Hold-current-pose skipped: arms do not expose a piper JointCtrl interface.")


def _home_arms_to_default(robot, teleop, speed: int = _PIPER_HOME_SLOW_SPEED) -> None:
    """第一个 episode 开始前：参考 reset.py，将主臂+从臂慢速归位到硬件初始(全零)位置。

    用 raw all-zero JointCtrl（绕过标定），两臂到达同一物理零位，使策略从一致、已同步的姿态
    起步，从根本上避免“主从臂不同步 + 首拍全速 slew”导致的危险急冲。主臂先退出重力补偿/可拖动
    模式、进入位置模式再下发。对不暴露 piper SDK 接口的臂静默跳过。
    """
    homed_any = False

    # 主臂：准备过程必须与 VLA(send_feedback) 完全一致。set_manual_control(False) 会退出重力补偿、
    # 进入 command_high_follow 模式(0xAD)并使能。先准备好主臂、确定 mit_mode，但延后实际下发——
    # 主臂在 0xAD 下 speed 不生效，单条 JointCtrl 会全速急冲，必须用 reset.py 的 control_arm_smooth
    # 方式插值慢速归位（见 _home_leader_arm_smooth）。这里按主臂自身配置选 mit_mode。
    leader_arm = None
    leader_mit_mode = 0x00
    if teleop is not None and not isinstance(teleop, list):
        candidate = getattr(teleop, "arm", None)
        if candidate is not None and hasattr(candidate, "JointCtrl"):
            if hasattr(teleop, "set_manual_control"):
                try:
                    teleop.set_manual_control(False)
                except Exception:
                    logging.exception("Failed to switch leader to command mode before homing.")
            leader_cfg = getattr(teleop, "config", None)
            leader_mit_mode = 0xAD if getattr(leader_cfg, "command_high_follow", False) else 0x00
            leader_arm = candidate

    # 从臂：不是 high-follow 模式，沿用 reset.py 风格的位置模式(0x00)归位即可，且 speed 生效。
    # 先下发（非阻塞，硬件自行运动），让它与随后阻塞插值的主臂并行归位。
    follower_arm = getattr(robot, "arm", None)
    if follower_arm is not None and hasattr(follower_arm, "JointCtrl"):
        _home_piper_arm(follower_arm, speed=speed)
        homed_any = True

    # 主臂：参考 reset.py 的 control_arm_smooth，从当前位姿插值、逐步小步慢速归位（阻塞约
    # duration_s 秒，期间从臂并行运动），从根本上避免 0xAD 下单条 JointCtrl 全速急冲的危险。
    if leader_arm is not None:
        _home_leader_arm_smooth(leader_arm, mit_mode=leader_mit_mode, speed=speed)
        homed_any = True

    if homed_any:
        # 主臂插值结束后再统一等待一次到位+稳定（从臂可能仍在收尾）。
        time.sleep(_PIPER_HOME_SETTLE_S)
        logging.info("First episode: leader + follower slowly homed to default (all-zero) pose.")
    else:
        logging.warning("Startup home skipped: arms do not expose a piper JointCtrl interface.")


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1'.
    # Use 'h264' for faster encoding on systems where AV1 encoding is CPU-heavy.
    vcodec: str = "libsvtav1"
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # In policy mode, broadcast the same robot action to the teleop arm via `teleop.send_feedback`.
    policy_sync_to_teleop: bool = False
    # Use parallel dispatch to reduce action broadcast latency when syncing policy to teleop.
    policy_sync_parallel: bool = True
    # Enable S0/S1/S2 intervention state machine when policy + teleop are both available.
    intervention_state_machine_enabled: bool = True
    # Keyboard key used to toggle entering/leaving intervention.
    intervention_toggle_key: str = "i"
    # Whether to capture episode-level success/failure labels from keyboard.
    enable_episode_outcome_labeling: bool = False
    # Keyboard key to mark the current episode as success and end it.
    episode_success_key: str = "s"
    # Keyboard key to mark the current episode as failure and end it.
    episode_failure_key: str = "f"
    # Optional keyboard key that aborts the current episode, drives the arms back to the stored
    # initial pose, and re-records the same episode from scratch. Disabled when None.
    reset_episode_key: str | None = None
    # Optional fallback label used when no explicit success/failure key was pressed.
    default_episode_success: str | None = None
    # When an episode ends because the max recording time was reached (timeout) without an explicit
    # success/failure label, controls how the arms behave afterwards:
    #   True  -> drive the arms back to the default (initial) pose (复位).
    #   False -> leave the arms where they are and just hold the current pose (保持原地不动).
    reset_on_timeout: bool = True
    # If True, require explicit or default episode labels before saving.
    require_episode_success_label: bool = False
    # Whether to record per-frame quality events (e.g. bad_depth/bad_edge) via configured hotkeys.
    enable_quality_event_labeling: bool = True
    # Path to the JSON event-config file describing the listened events and their key bindings
    # (one key may map to multiple events). If None, no quality events are recorded.
    event_config_path: str | None = None
    # Whether to store step-level collector policy provenance.
    enable_collector_policy_id: bool = False
    # Policy identifier used when action source is policy. If omitted, inferred from policy config.
    collector_policy_id_policy: str | None = None
    # Policy identifier used when action source is human/teleop.
    collector_policy_id_human: str = "human"
    # ACP inference controls for policy-driven recording.
    acp_inference: ACPInferenceConfig = field(default_factory=ACPInferenceConfig)
    # Retry timeout for transient communication errors (seconds). Set to 0 to fail immediately.
    communication_retry_timeout_s: float = 2.0
    # Sleep interval between communication retries (seconds).
    communication_retry_interval_s: float = 0.1

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")
        sanity_check_bimanual_piper_pair(self.robot, self.teleop)
        if not self.intervention_toggle_key or len(self.intervention_toggle_key) != 1:
            raise ValueError("`intervention_toggle_key` must be a single character.")

        if self.enable_episode_outcome_labeling:
            label_key_bindings = {
                "episode_success_key": self.episode_success_key,
                "episode_failure_key": self.episode_failure_key,
            }
            for key_name, key_value in label_key_bindings.items():
                if not key_value or len(key_value) != 1:
                    raise ValueError(f"`{key_name}` must be a single character.")

            normalized_keys = [
                self.intervention_toggle_key.lower(),
                self.episode_success_key.lower(),
                self.episode_failure_key.lower(),
            ]
            if len(set(normalized_keys)) != len(normalized_keys):
                raise ValueError(
                    "`intervention_toggle_key`, `episode_success_key`, and `episode_failure_key` must be distinct."
                )

        if self.default_episode_success is not None:
            self.default_episode_success = normalize_episode_success_label(self.default_episode_success)

        if not self.collector_policy_id_human:
            raise ValueError("`collector_policy_id_human` must be a non-empty string.")
        if self.acp_inference.use_cfg and not self.acp_inference.enable:
            raise ValueError("`acp_inference.use_cfg=true` requires `acp_inference.enable=true`.")
        if self.acp_inference.cfg_beta < 0:
            raise ValueError("`acp_inference.cfg_beta` must be >= 0.")
        if self.communication_retry_timeout_s < 0:
            raise ValueError("`communication_retry_timeout_s` must be >= 0.")
        if self.communication_retry_interval_s <= 0:
            raise ValueError("`communication_retry_interval_s` must be > 0.")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


def _ensure_human_inloop_compatible_features(
    dataset_features: dict[str, dict],
    *,
    action_feature_names: list[str],
) -> None:
    # Keep human-in-loop datasets schema-stable across teleop-only and policy-assisted phases so they can merge.
    dataset_features["complementary_info.policy_action"] = {
        "dtype": "float32",
        "shape": (len(action_feature_names),),
        "names": action_feature_names,
    }
    dataset_features["complementary_info.is_intervention"] = {
        "dtype": "float32",
        "shape": (1,),
        "names": ["is_intervention"],
    }
    dataset_features["complementary_info.state"] = {
        "dtype": "float32",
        "shape": (1,),
        "names": ["state"],
    }


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging(log_file=os.path.join(os.getcwd(), "inloop_record.log"), file_level="INFO")
    
    logging.info(
        "Human-in-loop recording is enabled. Press '%s' to toggle takeover. "
        "Press '%s' to mark success and end, '%s' to mark failure and end. "
        "Recorded `action` is the executed action. "
        "Policy output (when policy is enabled) is stored in `complementary_info.policy_action`. "
        "Collector source is stored in `complementary_info.collector_policy_id`. "
        "ACP inference: enable=%s use_cfg=%s cfg_beta=%.3f.",
        cfg.intervention_toggle_key,
        cfg.episode_success_key,
        cfg.episode_failure_key,
        cfg.acp_inference.enable,
        cfg.acp_inference.use_cfg,
        cfg.acp_inference.cfg_beta,
    )
    if cfg.require_episode_success_label and not cfg.enable_episode_outcome_labeling:
        raise ValueError(
            "`require_episode_success_label=true` requires `enable_episode_outcome_labeling=true`."
        )

    # Load the quality-event configuration (events + key bindings) from the JSON config file
    # passed down by the caller (e.g. lerobot_human_inloop_record.py). No file -> no events.
    event_config: EventConfig | None = None
    if cfg.enable_quality_event_labeling and cfg.event_config_path is not None:
        event_config = EventConfig.from_json(cfg.event_config_path)
        # The event hotkeys must not collide with the recording control keys.
        reserved_keys = {cfg.intervention_toggle_key.lower()}
        if cfg.enable_episode_outcome_labeling:
            reserved_keys |= {cfg.episode_success_key.lower(), cfg.episode_failure_key.lower()}
        if cfg.reset_episode_key:
            reserved_keys |= {cfg.reset_episode_key.lower()}
        conflicting = set(event_config.key_bindings) & reserved_keys
        if conflicting:
            raise ValueError(
                f"Event hotkeys {sorted(conflicting)} from {cfg.event_config_path} "
                "collide with intervention/success/failure keys."
            )
        logging.info(
            "Quality-event labeling enabled (source=%s): events=%s, key_bindings=%s",
            cfg.event_config_path,
            event_config.events,
            event_config.key_bindings,
        )

    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )
    logging.info(f"dataset_features: {dataset_features}")
    if cfg.teleop is not None:
        action_names = dataset_features[ACTION]["names"]
        action_names = list(robot.action_features) if action_names is None else list(action_names)
        _ensure_human_inloop_compatible_features(dataset_features, action_feature_names=action_names)
    if cfg.enable_collector_policy_id:
        dataset_features["complementary_info.collector_policy_id"] = {
            "dtype": "string",
            "shape": (1,),
            "names": ["collector_policy_id"],
        }
    if event_config is not None:
        # Per-frame event flags (one per configured event), written through add_frame in record_loop.
        dataset_features.update(event_config.build_features())
    logging.info(f"dataset_features: {dataset_features}")

    dataset = None
    listener = None
    policy_sync_executor = None

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            # sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
            )

        # Load pretrained policy
        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        if cfg.acp_inference.enable and cfg.policy is None:
            raise ValueError("`acp_inference.enable=true` requires `policy` to be set.")
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        collector_policy_id_policy = (
            cfg.collector_policy_id_policy
            if cfg.collector_policy_id_policy is not None
            else infer_collector_policy_id(cfg.policy)
        )
        collector_policy_id_human = cfg.collector_policy_id_human

        robot.connect()
        if teleop is not None:
            teleop.connect()
        logging.info("robot and teleop all conected")

        on_record_connected = getattr(cfg, "_on_record_connected", None)
        if callable(on_record_connected):
            on_record_connected(robot, teleop)  # 加载初始姿态

        if cfg.policy_sync_to_teleop:
            # 策略动作广播给主臂
            if cfg.policy is None:
                raise ValueError("`policy_sync_to_teleop=true` requires `policy` to be set.")
            if teleop is None or isinstance(teleop, list):
                raise ValueError(
                    "`policy_sync_to_teleop=true` requires exactly one teleoperator with send_feedback support."
                )
            policy_sync_executor = PolicySyncDualArmExecutor(
                robot=robot,
                teleop=teleop,
                parallel_dispatch=cfg.policy_sync_parallel,
            )

        listener, events = init_keyboard_listener(
            intervention_toggle_key=cfg.intervention_toggle_key,
            episode_success_key=cfg.episode_success_key if cfg.enable_episode_outcome_labeling else None,
            episode_failure_key=cfg.episode_failure_key if cfg.enable_episode_outcome_labeling else None,
            event_config=event_config,
            reset_episode_key=cfg.reset_episode_key,
        )

        with VideoEncodingManager(dataset):
            # 第一个 episode 开始前：参考 reset.py，把主从臂慢速归位到初始(全零)位置，
            # 仅在有策略模型时执行（纯人工示范无需归位）。让策略从一致、已同步的姿态起步。
            if policy is not None and not events["stop_recording"]:
                log_say("Homing arms to default pose", cfg.play_sounds)
                _home_arms_to_default(robot, teleop)

            recorded_episodes = 0
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                # 清空上一轮的成功/失败标签，开始新一轮录制
                events["episode_outcome"] = None
                events["episode_timeout"] = False
                # 本 episode 的质量事件列表，可为空；record_loop 会就地追加由事件配置文件中
                # 定义的热键所标记的事件，形如 {"step": <frame>, "event": <event_name>}。
                episode_events: list[dict] = []
                # episode开始的播报标签
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                # events["toggle_intervention"] = True  # MM
                # 主录制：逐帧add_frame写入buffer，内部超市或exit_early控制录制结束
                last_robot_action = record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    display_compressed_images=display_compressed_images,
                    policy_sync_executor=policy_sync_executor,
                    intervention_state_machine_enabled=cfg.intervention_state_machine_enabled,  # 启用接管状态机
                    collector_policy_id_policy=collector_policy_id_policy,
                    collector_policy_id_human=collector_policy_id_human,
                    acp_inference=cfg.acp_inference,
                    communication_retry_timeout_s=cfg.communication_retry_timeout_s,
                    communication_retry_interval_s=cfg.communication_retry_interval_s,
                    event_config=event_config,
                    episode_events=episode_events,
                )
                # return # MM

                # 仅采用显式 s/f 标注；未显式标注则为 None（下方据此放弃并重录该 episode）。
                episode_success = None
                if cfg.enable_episode_outcome_labeling:
                    episode_success = events.get("episode_outcome")

                # 达到最大录制时长（超时结束，而非按键提前结束）且未显式标注时：将该 episode 标记为失败
                # （或配置的默认标签）并保存，同时复位机械臂到初始位置。与 R 键一致，这里直接复用
                # `_home_arms_to_default`（首个 episode 启动时的同一归位例程，见上方），而不是走
                # `_on_record_reset_episode` 钩子 / 动作管线——避免刚结束的 episode 的历史残留状态
                # 影响落点，确保超时复位与最初的重置完全一致。
                homed_after_timeout = False
                if (
                    cfg.enable_episode_outcome_labeling
                    and episode_success is None
                    and events.get("episode_timeout")
                    and not events["stop_recording"]
                    and not events["rerecord_episode"]
                ):
                    episode_success = cfg.default_episode_success or EPISODE_FAILURE
                    if cfg.reset_on_timeout:
                        # 复位：与 R 键/最初复位完全一致，将机械臂慢速归位到初始(全零)位置。
                        log_say("Max episode time reached, marking episode as failure", cfg.play_sounds)
                        _home_arms_to_default(robot, teleop)
                        homed_after_timeout = True
                    else:
                        # 保持原地不动：仅标记为失败并保存，不归位。让下方的 _hold_arms_current_pose
                        # 分支接管，把主从臂锁定在超时结束时的当前位姿，保持到下一 episode 开始。
                        log_say(
                            "Max episode time reached, marking episode as failure (holding arms in place)",
                            cfg.play_sounds,
                        )

                # 每个 episode 结束（成功 s / 失败 f / 重录 ←）后，can0 复用 can1
                # 最后成功接收的动作保持，can1 继续锁定当前位姿。
                # 接管(按 i)不会结束 episode，因此不会触发这里。
                # 整体停止录制(Esc)时跳过，直接进入收尾/断开流程。
                #
                # 超时已归位时不再用上一拍动作覆盖归位结果。
                if not events["stop_recording"] and not homed_after_timeout:
                    log_say("Hold arms in place", cfg.play_sounds)

                    # reset g1 robot
                    if robot.name == "unitree_g1":
                        logging.info("Resetting Unitree G1 robot...")
                        robot.reset()

                    _hold_arms_current_pose(robot, teleop, last_robot_action)

                    # record_loop(  # policy preprocessor postprocessor dataset传空
                    #     robot=robot,
                    #     events=events,
                    #     fps=cfg.dataset.fps,
                    #     teleop_action_processor=teleop_action_processor,
                    #     robot_action_processor=robot_action_processor,
                    #     robot_observation_processor=robot_observation_processor,
                    #     teleop=teleop,
                    #     control_time_s=cfg.dataset.reset_time_s,
                    #     single_task=cfg.dataset.single_task,
                    #     display_data=cfg.display_data,
                    #     policy_sync_executor=policy_sync_executor,
                    #     intervention_state_machine_enabled=cfg.intervention_state_machine_enabled,
                    #     collector_policy_id_policy=collector_policy_id_policy,
                    #     collector_policy_id_human=collector_policy_id_human,
                    #     acp_inference=cfg.acp_inference,
                    #     communication_retry_timeout_s=cfg.communication_retry_timeout_s,
                    #     communication_retry_interval_s=cfg.communication_retry_interval_s,
                    # )

                # 放弃并重录当前 episode 的两种情况：
                #  1) 用户显式按 ← 要求重录；
                #  2) 开启成败标注但结束时未显式标注成功/失败（如按 → 提前结束）：直接放弃、不记录、重录。
                # 注意：超时结束（达到最大录制时长）已在上方被标记为失败并复位机械臂，episode_success 不再为
                # None，因此不会走到这里的放弃/重录分支，而是正常保存为失败样本。
                # 整体停止录制(Esc)不在此重录，交由下方决定是否丢弃。
                discard_unlabeled = (
                    cfg.enable_episode_outcome_labeling
                    and episode_success is None
                    and not events["stop_recording"]
                )
                if events["rerecord_episode"] or discard_unlabeled:
                    # 是否为用户显式按 ← 触发的重录（区别于「未标注成败被动放弃重录」）：
                    # 仅这种情况在重新开始记录前插入倒计时等待。下方会把该标志位清零，
                    # 故先在此捕获。
                    explicit_rerecord = bool(events["rerecord_episode"])
                    reset_requested = bool(events.get("reset_episode"))
                    if reset_requested:
                        log_say("Reset arms to initial pose and re-record episode", cfg.play_sounds)
                    elif events["rerecord_episode"]:
                        log_say("Re-record episode", cfg.play_sounds)
                    else:
                        log_say("No success or failure label, re-record episode", cfg.play_sounds)
                        logging.warning(
                            "Episode has no explicit success/failure label; discarding and re-recording."
                        )

                    # On an explicit reset (R key), drive the arms back to the initial pose before
                    # restarting the episode. We deliberately reuse `_home_arms_to_default` — the exact
                    # same routine used for the first episode at startup (see above) — instead of the
                    # `_on_record_reset_episode` hook. The hook resets via robot.send_action /
                    # teleop.send_feedback, i.e. the normal action pipeline, which carries residual
                    # state from the just-finished episode (last-action / calibration round-trip /
                    # high-follow 0xAD behaviour) and makes R land somewhere different from the initial
                    # homing. Talking to the piper SDK with raw all-zero joints bypasses that history so
                    # R reproduces the initial reset exactly.
                    if reset_requested:
                        _home_arms_to_default(robot, teleop)

                    events["reset_episode"] = False
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    events["episode_outcome"] = None
                    episode_events.clear()
                    dataset.clear_episode_buffer()
                    # 用户显式按 ← 要求重录时，不立刻重新开始，先等待 _RERECORD_DELAY_S 秒
                    # （命令行逐秒倒计时提示）给操作者复位/准备的时间，再进入下一次记录。
                    if explicit_rerecord and not events["stop_recording"]:
                        _countdown_before_rerecord(_RERECORD_DELAY_S, cfg.play_sounds)
                    continue

                # 走到这里：要么有显式标注，要么未开启标注。若开启标注却仍无显式标注
                # （只可能是 Esc 停止录制时），放弃当前 episode、不保存。
                if cfg.enable_episode_outcome_labeling and episode_success is None:
                    logging.warning(
                        "Stopping without a success/failure label; discarding current episode (not saved)."
                    )
                    dataset.clear_episode_buffer()
                    continue

                extra_episode_metadata = {}
                if cfg.enable_episode_outcome_labeling:
                    extra_episode_metadata["episode_success"] = episode_success
                if event_config is not None:
                    # Store the per-episode event list ([{step, event}, ...]) as a JSON string so it
                    # round-trips safely through the parquet episode metadata.
                    extra_episode_metadata["quality_events"] = event_config.serialize(episode_events)
                    if episode_events:
                        logging.info(
                            "Episode %s recorded %d quality event(s): %s",
                            dataset.num_episodes,
                            len(episode_events),
                            episode_events,
                        )
                dataset.save_episode(extra_episode_metadata=extra_episode_metadata or None)
                recorded_episodes += 1
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            dataset.finalize()
            logging.info(
                "To inspect the recorded dataset, run:\n"
                "  lerobot-dataset-report --dataset %s",
                dataset.repo_id,
            )

        if policy_sync_executor is not None:
            policy_sync_executor.shutdown()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if listener and hasattr(listener, "stop"):
            listener.stop()

        if cfg.dataset.push_to_hub:
            if dataset is not None:
                dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)
            else:
                logging.warning(
                    "`dataset.push_to_hub=true` was requested, but dataset was not initialized due to an earlier error."
                )

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
